apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: rpg-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: demoapp88985792.azurecr.io/frontend:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: rpg-test
imagePullSecrets:
- name: pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: rpg-test
spec:
  type: ClusterIP
  ports:
  - name: frontend
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
