apiVersion: v1
kind: Namespace
metadata:
  name: game-pg-cluster
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: game-pg-cluster
  namespace: game-pg-cluster
spec:
  instances: 3
  storage:
    size: 1Gi
